<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
    <PackageReference Include="Hangfire.Core" Version="1.*" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.*" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.*" />
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Database\Seeds\**\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Seeds\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HrastERP.Infrastructure.Tests" />
    <InternalsVisibleTo Include="HrastERP.API" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HrastERP.SharedKernel\HrastERP.SharedKernel.csproj" />
  </ItemGroup>

</Project>
